apiVersion: apps/v1
kind: Deployment

metadata:
  name: predict-sentiment-api-minikube
  labels:
    app: predict-sentiment-api
spec:
  selector:
    matchLabels:
      app: predict-sentiment-api
  template:
    metadata:
      labels:
        app: predict-sentiment-api
    spec:
      containers:
      - name: predict-sentiment-api
        image: iad.ocir.io/idoulk58kp4z/predict-sentiment:latest
        env:
          - name: TRANSLATIONAPI_LB_IP
            value: $TRANSLATIONAPI_LB_IP
        resources:
          requests:
            memory: "4Gi"
        ports:
        - containerPort: 8080

